paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  unfeatured:
    path: essays
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  design:
    path: notes
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  adventures:
    path: adventures
    output: true
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
  data:
    path: _data
    output: false
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
  notes:
    path: notes
    output: false
    url:
    filter:
    parse_branch_index:
    name: Notes
    description: ''
    icon: notes
    documentation:
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
data_config: {}
timezone: Etc/UTC
