[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "/feed/notes.xml"
  to = "/feed/feed.xml"

[[redirects]]
  from = "/essays"
  to = "/stories"

[[redirects]]
  from = "/essays/*"
  to = "/stories/*"

[[redirects]]
  from = "/feed.xml"
  to = "/feed/feed.xml"
